### PR TITLE
Cleaned up ReadMe.md

### PR DESCRIPTION
**Pull request by Exohayvan**
If you want the discord badge to work you would have to turn on widgets but the rest is already to go :)

### CODE REVIEW

**Comment by Exohayvan** [comment]
I was also looking to help you with automatically building the exe but I would need some insight on what you need/want for that

**Comment by Exohayvan** [comment]
Have added tow Issue Templates to make issues more organized :)

**Comment by Exohayvan** [comment]
Added a workflow that auto compiles your script. It’s been tested.

So this PR now has:
- Improved Readme.md
- Issue Templates to make issues easier to read and work with.
- Automatic script build/compile (can automatically release them as well if needed)

**Comment by ItsLogic** [comment]
Thanks very much for this. Im going to make a few changes and then merging.
I will be removing the build.yml (I hope you didnt put too much work into it) Might look into it again in the future but for now I want to stay away from automated builds.
I'm also going to replace the issue and feature templates with simpler and more user friendly versions using the built in github UI elements.

**Pull request merged**
