### PR TITLE
More Games

### PR DESCRIPTION
**Pull request by NextLVLHasH**
Adds windows titles of the telltale games

### CODE REVIEW

**Comment by ItsLogic** [comment]
Can you list the games added so I can properly merge and fix the json files as some of them don't include "REPLACESEQ"

**Comment by NextLVLHasH** [comment]
Walking Dead Season one 
MC Story Mode season 1
MC Story Mode season 2
Marvels Guardians of the Galaxy
Batman season 1
Evil within 1 70-71 as idk why the first achievement isnt popping
Cities Skylines

**Comment by NextLVLHasH** [comment]
831464817 - Walking Dead Season 1; all achievements
849609009 - Minecraft Season 1; all achievements
148376670 - Minecraft Season 2; all achievements
832828665 - Batman Season 1; all achievements
360551610 - Batman Season 2; all achievements
1041197334 - Guardians of the Galaxy; all achievements
513025136 - Wolf Amoung us; all achievements
748474487 - Cities Skylines; all achievements
2095867988 - Evil Within 1; 70-71
927474846 - Firewatch; 9-10
651668093 - Resident Evil 7; 5-58 Work in progress

**Comment by NextLVLHasH** [comment]
Fuck Forza Achievements

**Comment by ItsLogic** [comment]
manually merged in 38add00f61149e0441dcac1cf21d3e7c69599b1c

**Pull request closed without merging**
