### PR TITLE
Fix GamePass Membership, Add Xbox Badges

### PR DESCRIPTION
**Pull request by asutermo**
- Gets proper Gamepass status
None
GPU

- Starts work for adding badges
Badges

- Minor code tweaks to home view model

### CODE REVIEW

**Comment by asutermo** [comment]
Badges partially work now. Some of the special badges do not yet.
image

**Comment by asutermo** [comment]
Casing fixed: 
image

**Comment by szaaamerik** [comment]
@asutermo I'm having trouble. 

image

it seems like the field doesn't exist?

image

not shown here either.

**Comment by asutermo** [comment]
Brand new account? Perhaps those fields aren't filled in. Thanks for the call out. Will look monday on an alt.

**Comment by szaaamerik** [comment]
It is not a brand new account, I don't think at least. It's my friends, but it does have game pass ultimate. I will debug it and see if I can get it working

image

**Comment by szaaamerik** [comment]
ok so I did some digging and I got the response.

```
{
  "errorCode": 1113,
  "data": {
    "hasProgramAccess": false,
    "hasActivities": false,
    "gamePassMembership": "Ultimate",
    "unclaimedBalance": 0,
    "modalActivityId": null,
    "balance": 0
  }
}
```

the fix for me was to change `gpu.gamePassMembership` to `gpu.data.gamePassMembership`. maybe it's different for old(er) accounts?

**Comment by szaaamerik** [comment]
ok I've came up with this. it seems to work fine for me

```
Gamepass = string.IsNullOrEmpty(gpu.gamePassMembership)
    ? $"Gamepass: {gpu.data.gamePassMembership}"
    : $"Gamepass: {gpu.gamePassMembership}";
```

**Comment by asutermo** [comment]
Good find!

**Pull request merged**
